language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no

install:
  - conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pytest-cov
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]; then
        conda install --yes -n testenv flake8;
    fi
  - source activate testenv
  - pip install future six h5py lmfit matplotlib codecov

script:
  - py.test --cov=idpflex idpflex tests
  - if [[ "${TRAVIS_PYTHON_VERSION}" == "3.6" ]]; then
        flake8;
    fi

after_success:
  - codecov

notifications:
  - on_success: never
  - on_failure: never
